# Sprint 4: Continuous Testing Configuration

# Test execution configuration
execution:
  # Maximum parallel test suites
  max_parallel_suites: 3
  
  # Default test timeout (in minutes)
  default_timeout: 45
  
  # Retry configuration
  retry:
    max_attempts: 2
    delay_seconds: 10
  
  # Environment-specific settings
  environments:
    dev:
      timeout: 30
      max_parallel_suites: 2
    staging:
      timeout: 45
      max_parallel_suites: 3
    production:
      timeout: 60
      max_parallel_suites: 1

# Test suite configuration
test_suites:
  terraform_validation:
    description: "Validate Terraform configurations and plans"
    priority: 1
    timeout: 15
    dependencies: []
    tags: ["infrastructure", "validation"]
    
  flink_transformation_tests:
    description: "Test Flink SQL transformations and data processing"
    priority: 2
    timeout: 45
    dependencies: ["terraform_validation"]
    tags: ["flink", "transformation", "sql"]
    
  streaming_tests:
    description: "Test streaming data flow and real-time processing"
    priority: 3
    timeout: 60
    dependencies: ["flink_transformation_tests"]
    tags: ["streaming", "realtime", "kafka"]
    
  performance_validation_tests:
    description: "Validate performance and load characteristics"
    priority: 4
    timeout: 90
    dependencies: ["streaming_tests"]
    tags: ["performance", "load", "benchmarking"]
    
  connector_tests:
    description: "Test connector functionality and data formats"
    priority: 2
    timeout: 30
    dependencies: ["terraform_validation"]
    tags: ["connectors", "smt", "schema"]
    
  e2e_flink_flow:
    description: "End-to-end Flink transformation flow testing"
    priority: 5
    timeout: 75
    dependencies: ["flink_transformation_tests", "streaming_tests"]
    tags: ["e2e", "flink", "integration"]

# Change detection configuration
change_detection:
  # File patterns to monitor for changes
  watch_patterns:
    - "terraform/**/*.tf"
    - "terraform/**/*.tftest.hcl"
    - "flink/**/*.sql"
    - "scripts/**/*.sh"
    - "config/**/*.yaml"
    - "continuous-testing/**/*"
  
  # Change impact mapping
  impact_mapping:
    "terraform/modules/flink-*":
      affects: ["flink_transformation_tests", "streaming_tests", "e2e_flink_flow"]
    "terraform/modules/compute-pool/*":
      affects: ["flink_transformation_tests", "performance_validation_tests"]
    "flink/sql/transformations/*":
      affects: ["flink_transformation_tests", "e2e_flink_flow"]
    "terraform/tests/flink/*":
      affects: ["flink_transformation_tests", "streaming_tests"]
    "scripts/smt-*":
      affects: ["connector_tests"]
    "config/*":
      affects: ["terraform_validation"]

# Quality gates
quality_gates:
  # Minimum success rate required
  min_success_rate: 85.0
  
  # Maximum allowed execution time (minutes)
  max_execution_time: 180
  
  # Critical test suites that must pass
  critical_suites:
    - "terraform_validation"
    - "flink_transformation_tests"
  
  # Performance thresholds
  performance:
    max_transformation_latency_ms: 5000
    min_throughput_records_per_sec: 1000
    max_memory_usage_mb: 2048

# Notification configuration
notifications:
  # Slack configuration
  slack:
    enabled: true
    webhook_url: "${SLACK_WEBHOOK_URL}"
    channels:
      success: "#sprint4-tests-success"
      failure: "#sprint4-tests-alerts"
    
  # Email configuration
  email:
    enabled: false
    smtp_server: "smtp.company.com"
    recipients:
      - "team@company.com"
  
  # Teams configuration
  teams:
    enabled: false
    webhook_url: "${TEAMS_WEBHOOK_URL}"

# Reporting configuration
reporting:
  # Report formats to generate
  formats: ["html", "json", "junit"]
  
  # Report retention (days)
  retention_days: 30
  
  # Include coverage information
  include_coverage: true
  
  # Include trend analysis
  include_trends: true
  
  # Report storage configuration
  storage:
    local_path: "test-reports"
    s3_bucket: "${TEST_REPORTS_S3_BUCKET:-}"
    upload_to_s3: false

# GitLab CI/CD integration
gitlab_ci:
  # Pipeline configuration
  pipeline:
    # Trigger conditions
    triggers:
      - push
      - merge_request
      - schedule
    
    # Branch-specific settings
    branches:
      main:
        run_all_tests: true
        quality_gates: true
      develop:
        smart_selection: true
        quality_gates: false
      feature/*:
        smart_selection: true
        quality_gates: false
  
  # Job configuration
  jobs:
    test_parallel_jobs: 3
    artifact_retention: "1 week"
    allow_failure_for:
      - "performance_validation_tests"

# Advanced features
advanced:
  # Smart test selection
  smart_selection:
    enabled: true
    algorithm: "dependency_aware"
    
    # Confidence threshold for test selection
    confidence_threshold: 0.7
    
    # Fallback to full suite if uncertainty is high
    fallback_threshold: 0.5
  
  # Test result caching
  caching:
    enabled: true
    cache_duration_hours: 24
    cache_key_factors:
      - "git_commit_hash"
      - "terraform_module_checksums"
      - "sql_file_checksums"
  
  # Parallel execution
  parallel_execution:
    enabled: true
    max_workers: 3
    load_balancing: "round_robin"
  
  # Flaky test detection
  flaky_test_detection:
    enabled: true
    failure_threshold: 0.2  # 20% failure rate
    retry_count: 3
    quarantine_duration_days: 7

# Monitoring and metrics
monitoring:
  # Test execution metrics
  metrics:
    enabled: true
    export_to_prometheus: false
    
    # Custom metrics to collect
    custom_metrics:
      - name: "flink_job_execution_time"
        type: "histogram"
        description: "Flink job execution duration"
      
      - name: "transformation_accuracy"
        type: "gauge"
        description: "Data transformation accuracy percentage"
      
      - name: "test_suite_success_rate"
        type: "gauge"
        description: "Test suite success rate over time"
  
  # Health checks
  health_checks:
    enabled: true
    interval_minutes: 5
    endpoints:
      - name: "confluent_cloud_api"
        url: "https://api.confluent.cloud/health"
      - name: "schema_registry"
        url: "${SCHEMA_REGISTRY_URL}/health"

# Security configuration
security:
  # Secret management
  secrets:
    vault_enabled: false
    environment_variables:
      - "CONFLUENT_CLOUD_API_KEY"
      - "CONFLUENT_CLOUD_API_SECRET"
      - "SLACK_WEBHOOK_URL"
  
  # Access control
  access_control:
    require_approval_for:
      - "production_tests"
      - "performance_tests"
    
    # Allowed users/groups
    authorized_users:
      - "sprint4-team"
      - "platform-engineers"

# Debug and troubleshooting
debug:
  # Enable verbose logging
  verbose_logging: false
  
  # Log retention
  log_retention_days: 14
  
  # Debug artifacts
  preserve_artifacts: true
  artifact_types:
    - "terraform_plans"
    - "flink_job_logs"
    - "test_output"
    - "performance_profiles"
