# Sprint 4: Quality Gates Configuration
# Defines quality gates and thresholds for continuous testing

# Overall quality gates configuration
quality_gates:
  # Global quality thresholds
  global_thresholds:
    # Test execution success rates
    minimum_test_success_rate: 95.0
    critical_test_success_rate: 100.0
    
    # Performance thresholds
    maximum_test_execution_time: "120m"
    maximum_single_test_time: "45m"
    
    # Coverage requirements
    minimum_code_coverage: 80.0
    minimum_critical_path_coverage: 100.0
    
    # Reliability thresholds
    maximum_flaky_test_rate: 5.0
    minimum_test_stability: 90.0

  # Sprint 4 specific quality gates
  sprint4_gates:
    flink_transformation_quality:
      # Data accuracy requirements
      minimum_data_completeness: 99.9
      maximum_data_error_rate: 0.1
      minimum_join_success_rate: 95.0
      maximum_late_data_percentage: 5.0
      
      # Performance requirements
      minimum_throughput_events_per_second: 1000
      maximum_processing_latency_seconds: 5
      maximum_checkpoint_duration_seconds: 30
      minimum_job_uptime_percentage: 99.0
      
      # Resource utilization limits
      maximum_cpu_utilization: 85.0
      maximum_memory_utilization: 90.0
      maximum_cfu_utilization: 80.0
    
    continuous_testing_quality:
      # Pipeline execution requirements
      maximum_pipeline_duration: "90m"
      minimum_parallel_efficiency: 70.0
      maximum_queue_wait_time: "5m"
      
      # Test selection accuracy
      minimum_test_selection_accuracy: 95.0
      maximum_unnecessary_test_rate: 10.0
      
      # Reliability requirements
      maximum_pipeline_failure_rate: 2.0
      minimum_test_result_consistency: 98.0

# Environment-specific quality gates
environment_gates:
  development:
    relaxed_thresholds:
      minimum_test_success_rate: 90.0
      maximum_test_execution_time: "60m"
      minimum_code_coverage: 70.0
    
    skip_non_critical: true
    allow_flaky_tests: true
    
  staging:
    standard_thresholds:
      minimum_test_success_rate: 95.0
      maximum_test_execution_time: "90m"
      minimum_code_coverage: 85.0
    
    skip_non_critical: false
    allow_flaky_tests: false
    
  production:
    strict_thresholds:
      minimum_test_success_rate: 99.0
      maximum_test_execution_time: "45m"
      minimum_code_coverage: 90.0
      critical_test_success_rate: 100.0
    
    skip_non_critical: false
    allow_flaky_tests: false
    require_manual_approval: true

# Test category specific gates
category_gates:
  # Terraform validation gates
  terraform_validation:
    success_rate_threshold: 100.0
    max_execution_time: "5m"
    required_checks:
      - "terraform_fmt_check"
      - "terraform_validate"
      - "terraform_plan"
    blocking: true
  
  # Flink transformation gates
  flink_transformations:
    success_rate_threshold: 98.0
    max_execution_time: "30m"
    performance_gates:
      min_throughput: 500  # events per second
      max_latency: 10      # seconds
      max_checkpoint_time: 60  # seconds
    data_quality_gates:
      min_completeness: 99.0
      max_error_rate: 1.0
      min_accuracy: 99.5
    blocking: true
  
  # Schema and data format gates
  data_format_validation:
    success_rate_threshold: 100.0
    max_execution_time: "10m"
    format_compliance:
      avro_validation: true
      json_schema_validation: true
      protobuf_validation: true
    blocking: true
  
  # Security validation gates
  security_validation:
    success_rate_threshold: 100.0
    max_execution_time: "15m"
    security_checks:
      rbac_validation: true
      acl_validation: true
      secret_scanning: true
      vulnerability_scanning: true
    blocking: true
  
  # Performance testing gates
  performance_testing:
    success_rate_threshold: 95.0
    max_execution_time: "45m"
    performance_benchmarks:
      min_throughput_improvement: 0  # no regression
      max_latency_degradation: 10    # 10% max degradation
      max_memory_increase: 20        # 20% max increase
    blocking: false  # Non-blocking for feature branches
  
  # End-to-end testing gates
  e2e_testing:
    success_rate_threshold: 98.0
    max_execution_time: "60m"
    data_flow_validation:
      producer_consumer_accuracy: 100.0
      connector_data_integrity: 99.9
      transformation_accuracy: 99.5
    blocking: true

# Merge request quality gates
merge_request_gates:
  # Required for all merge requests
  mandatory_checks:
    - name: "terraform_validation"
      blocking: true
      timeout: "5m"
    
    - name: "basic_functionality"
      blocking: true
      timeout: "15m"
    
    - name: "security_scan"
      blocking: true
      timeout: "10m"
  
  # Required for main branch merges
  main_branch_additional:
    - name: "performance_regression_check"
      blocking: true
      timeout: "30m"
    
    - name: "full_e2e_validation"
      blocking: true
      timeout: "45m"
    
    - name: "data_accuracy_validation"
      blocking: true
      timeout: "20m"
  
  # Quality score calculation
  quality_score:
    # Weighted components
    test_success_rate: 40
    code_coverage: 20
    performance_metrics: 15
    security_score: 15
    documentation_score: 10
    
    # Minimum score to pass
    minimum_passing_score: 80
    minimum_main_branch_score: 90

# Scheduled testing quality gates
scheduled_gates:
  nightly_testing:
    comprehensive_coverage: true
    include_performance_benchmarks: true
    include_stress_tests: true
    
    quality_requirements:
      minimum_test_success_rate: 98.0
      maximum_execution_time: "180m"
      minimum_coverage: 95.0
    
    failure_handling:
      auto_retry: true
      max_retries: 2
      notify_on_failure: true
      create_issues_on_repeated_failure: true
  
  weekly_testing:
    full_regression_suite: true
    include_load_tests: true
    include_chaos_engineering: true
    
    quality_requirements:
      minimum_test_success_rate: 95.0
      maximum_execution_time: "360m"
      minimum_coverage: 90.0

# Performance quality gates
performance_gates:
  # Flink job performance
  flink_performance:
    throughput_benchmarks:
      user_enrichment: 2000  # events/second
      event_aggregation: 1500
      windowed_analytics: 1000
    
    latency_benchmarks:
      max_processing_latency: 5    # seconds
      max_window_trigger_delay: 10 # seconds
      max_join_latency: 3         # seconds
    
    resource_utilization:
      max_cpu_per_cfu: 80    # percentage
      max_memory_per_cfu: 85 # percentage
      max_checkpoint_overhead: 10 # percentage
  
  # System performance
  system_performance:
    api_response_times:
      confluent_api_max: 5000    # milliseconds
      terraform_operations_max: 30000  # milliseconds
    
    resource_creation_times:
      topic_creation_max: 60     # seconds
      connector_deployment_max: 180  # seconds
      flink_job_startup_max: 120 # seconds

# Data quality gates
data_quality_gates:
  # Transformation accuracy
  transformation_accuracy:
    field_mapping_accuracy: 100.0
    data_type_conversion_accuracy: 99.9
    aggregation_accuracy: 99.8
    join_accuracy: 99.5
  
  # Data completeness
  data_completeness:
    message_delivery_rate: 99.9
    schema_compliance_rate: 100.0
    referential_integrity_rate: 99.5
  
  # Data freshness
  data_freshness:
    max_processing_delay: 30    # seconds
    max_aggregation_delay: 300  # seconds for windowed operations
    max_join_staleness: 60      # seconds

# Reliability quality gates
reliability_gates:
  # Test stability
  test_stability:
    max_flaky_test_percentage: 5.0
    min_test_consistency_rate: 95.0
    max_false_positive_rate: 2.0
  
  # Infrastructure reliability
  infrastructure_reliability:
    max_resource_creation_failure_rate: 1.0
    max_job_failure_rate: 2.0
    min_service_availability: 99.9
  
  # Recovery capabilities
  recovery_capabilities:
    max_recovery_time: 300      # seconds
    checkpoint_recovery_success_rate: 99.0
    auto_restart_success_rate: 95.0

# Notification and alerting gates
notification_gates:
  # Alert thresholds
  alert_thresholds:
    critical_test_failure: "immediate"
    performance_degradation: "15m"
    quality_gate_failure: "immediate"
    flaky_test_detection: "24h"
  
  # Escalation rules
  escalation_rules:
    - condition: "critical_failure"
      notify: ["team_lead", "on_call_engineer"]
      escalate_after: "5m"
    
    - condition: "quality_gate_failure"
      notify: ["development_team"]
      escalate_after: "15m"
    
    - condition: "performance_degradation"
      notify: ["performance_team"]
      escalate_after: "30m"

# Reporting and metrics gates
reporting_gates:
  # Metrics collection requirements
  metrics_collection:
    test_execution_metrics: true
    performance_metrics: true
    resource_utilization_metrics: true
    quality_metrics: true
  
  # Report generation requirements
  report_generation:
    test_execution_reports: true
    performance_trend_reports: true
    quality_trend_reports: true
    failure_analysis_reports: true
  
  # Data retention
  data_retention:
    test_results: "90d"
    performance_metrics: "180d"
    quality_metrics: "365d"
    failure_logs: "30d"
